openapi: 3.0.0
servers:
  - url: http://127.0.0.1:9010
info:
  title: Sample API
  version: 1.0.0
  description: The response type of APIs are wrapped by "BaseResponse" type
tags:
  - name: User
    description: User operations
paths:
  /user:
    $ref: user.yml
  /role:
    $ref: role.yml
components:
  schemas:
    $ref: schemas.yml
  securitySchemes:
    $ref: securitySchemes.yml
