get:
  summary: Get user by ID
  tags:
    - User
  parameters:
    - name: id
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
  responses:
    200:
      content:
        application/json:
          schema:
            $ref: "schemas.yml/#/User"
    500:
      content:
        application/problem+json:
          schema:
            $ref: "schemas.yml/#/ErrorDetails"
